### ISSUE TITLE
Error When initializing the client

### ISSUE THREAD

**Issue by TheLazyLemur** [supabase/supabase-csharp#4]
# Bug report

## Describe the bug

When calling 
 ```cs
await Supabase.Client.InitializeAsync(url, key);
```
I get the error 
```
2021/05/26 18:48:17|Fatal|WebSocket.connect|WebSocketSharp.WebSocketException: Not a WebSocket handshake response.
                             at WebSocketSharp.WebSocket.doHandshake()
                             at WebSocketSharp.WebSocket.connect()
Unhandled exception. System.Exception: Error occurred connecting to Socket. Check logs.
   at Supabase.Client.InitializeAsync(String supabaseUrl, String supabaseKey, SupabaseOptions options)
   at Supabase.AsyncHelper.RunSync[TResult](Func`1 func)
   at Supabase.Client.Initialize(String supabaseUrl, String supabaseKey, SupabaseOptions options)
   at SupaSharp.Program.Main(String[] args) in /home/dan/Workspace/Personal/SupaSharp/SupaSharp/Program.cs:line 21
   at SupaSharp.Program.<Main>(String[] args)

Process finished with exit code 134
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new Console app
2. Add this code
```cs
    class Program
    {
        static async Task Main(string[] args)
        {
            var url = "<URL>";
            var key = "<KEY>";

            await Supabase.Client.InitializeAsync(url, key);
        }
    }
```
3. Run App

## Expected behavior

The client to initialize without error

**Comment by TheLazyLemur** [comment]
Since the version change to 0.1.5 that specific error has changed, to a null reference exception on the instance object.

My Code:
```cs
        static void Main(string[] args)
        {
            var url = "https://hhrlrnbaffbvmbucwvjz.supabase.co/rest/v1/";
            var key =
                "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMjAzMDA5NywiZXhwIjoxOTM3NjA2MDk3fQ.olKa_4hUbhnu6L74ogh-u1cJnt5wd8a4i8elws_pFic";

            Client.Initialize(url, key);

            var instance = Supabase.Client.Instance;

            Console.WriteLine(instance.SupabaseKey);
        }```

The Error:
```cs
/home/dan/Workspace/Personal/SupaSharp/SupaSharp/bin/Debug/net5.0/SupaSharp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SupaSharp.Program.Main(String[] args) in /home/dan/Workspace/Personal/SupaSharp/SupaSharp/Program.cs:line 27

Process finished with exit code 134.
```

**Comment by acupofjose** [comment]
Ah - your URL should just be `https://hhrlrnbaffbvmbucwvjz.supabase.co`

For Example:
```c#

static async Task Main(string[] args)
        {
            var url = "https://hhrlrnbaffbvmbucwvjz.supabase.co/rest/v1/";
            var key = "";

            await Supabase.Client.InitializeAsync(url, key, new Supabase.SupabaseOptions { AutoConnectRealtime = true, ShouldInitializeRealtime = true });

            var reference = Supabase.Client.Instance.From<Models.Channel>();

            await reference.On(Supabase.Client.ChannelEventType.All, (sender, ev) =>
            {
                Debug.WriteLine($"[{ev.Response.Event}]:{ev.Response.Topic}:{ev.Response.Payload.Record}");
            });

            await reference.Insert(new Models.Channel { Slug = GenerateName(10), InsertedAt = DateTime.Now });

            Console.ReadLine();
        }
```

**Comment by TheLazyLemur** [comment]
Thank you that works.

A heads up that having an extra slash at then end of the URL causes the error as well.

Is this project open for contributions?

**Comment by acupofjose** [comment]
Absolutely it is - I would love contributions!

**Comment by TheLazyLemur** [comment]
Is there something missing when it comes to realtime events?

my code:

```
cs
            await Client.InitializeAsync(url, key, new SupabaseOptions
            {
                AutoConnectRealtime = true,
                ShouldInitializeRealtime = true
            });

            var instance = Client.Instance;

            var newExp = new EdenExperience
            {
                Uuid = Guid.NewGuid().ToString(),
                Ownerid = Guid.NewGuid().ToString(),
                Name = "Test",
                ExperiencePayload = "{}"
            };

            var table = instance.From<EdenExperience>();
            await table.On(Client.ChannelEventType.All, OnDbInteracted);
            await table.Insert(newExp);
            Console.ReadLine();

        private void OnDbInteracted(object arg1, SocketResponseEventArgs arg2)
        {
            Debug.WriteLine($"[{arg2.Response.Event}]:{arg2.Response.Topic}:{arg2.Response.Payload.Record}");
        }
```

However no action triggers

**Comment by acupofjose** [comment]
Is replication enabled on the table (https://supabase.io/docs/guides/auth#disable-realtime-for-private-tables)? (This link shows disabling, but also the enable command)

Are you seeing the inserted record in the database?

**Comment by TheLazyLemur** [comment]
Ive done this

```
alter publication supabase_realtime add table eden_experience;
```

**Comment by TheLazyLemur** [comment]
Okay Ive got it! thanks for all your help
